[package]
name = "listdevices"
version = "0.1.0"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.12"
cpal = "0.12.1"
